import type { BlockDefinition } from "./types";

// Схемы блоков. Панель настроек рендерится автоматически из `fields`.
// Значения по умолчанию живут в `defaultProps` (используются при добавлении блока).

export const blockDefinitions: BlockDefinition[] = [
  {
    type: "header",
    name: "Шапка (навигация)",
    category: "Структура",
    defaultProps: {
      logo: "Логотип",
      buttonText: "Начать",
      showButton: true,
      bg: "#ffffff",
      textColor: "#111827",
      buttonColor: "#2563eb",
      buttonTextColor: "#ffffff",
    },
    fields: [
      { type: "text", key: "logo", label: "Логотип", group: "content" },
      { type: "text", key: "buttonText", label: "Текст кнопки", group: "content" },
      { type: "toggle", key: "showButton", label: "Показывать кнопку", group: "content" },
      { type: "color", key: "bg", label: "Фон", group: "style" },
      { type: "color", key: "textColor", label: "Цвет текста", group: "style" },
      { type: "color", key: "buttonColor", label: "Цвет кнопки", group: "style" },
      { type: "color", key: "buttonTextColor", label: "Цвет текста кнопки", group: "style" },
    ],
  },
  {
    type: "hero",
    name: "Обложка (Hero)",
    category: "Структура",
    defaultProps: {
      eyebrow: "Добро пожаловать",
      title: "Заголовок вашего сайта",
      subtitle: "Краткое описание того, что вы предлагаете. Расскажите посетителю, почему это важно.",
      primaryText: "Начать",
      secondaryText: "Подробнее",
      showSecondary: true,
      image: "",
      showImage: false,
      bg: "#111827",
      textColor: "#ffffff",
      accent: "#2563eb",
      align: "center",
      paddingY: 96,
    },
    fields: [
      { type: "text", key: "eyebrow", label: "Надзаголовок", group: "content" },
      { type: "text", key: "title", label: "Заголовок", group: "content" },
      { type: "textarea", key: "subtitle", label: "Подзаголовок", group: "content" },
      { type: "text", key: "primaryText", label: "Текст главной кнопки", group: "content" },
      { type: "toggle", key: "showSecondary", label: "Вторая кнопка", group: "content" },
      { type: "text", key: "secondaryText", label: "Текст второй кнопки", group: "content" },
      { type: "toggle", key: "showImage", label: "Показывать картинку", group: "content" },
      { type: "image", key: "image", label: "Картинка", aspect: "video", group: "content" },
      { type: "align", key: "align", label: "Выравнивание", group: "style" },
      { type: "color", key: "bg", label: "Фон", group: "style" },
      { type: "color", key: "textColor", label: "Цвет текста", group: "style" },
      { type: "color", key: "accent", label: "Акцентный цвет", group: "style" },
      { type: "number", key: "paddingY", label: "Вертикальный отступ", unit: "px", min: 0, max: 240, step: 8, group: "style" },
    ],
  },
  {
    type: "features",
    name: "Преимущества",
    category: "Контент",
    defaultProps: {
      title: "Наши преимущества",
      subtitle: "Почему выбирают нас",
      f1Title: "Быстро",
      f1Text: "Короткое описание первого преимущества.",
      f2Title: "Надёжно",
      f2Text: "Короткое описание второго преимущества.",
      f3Title: "Просто",
      f3Text: "Короткое описание третьего преимущества.",
      bg: "#f9fafb",
      textColor: "#111827",
      accent: "#2563eb",
    },
    fields: [
      { type: "text", key: "title", label: "Заголовок", group: "content" },
      { type: "text", key: "subtitle", label: "Подзаголовок", group: "content" },
      { type: "text", key: "f1Title", label: "Заголовок 1", group: "content" },
      { type: "textarea", key: "f1Text", label: "Текст 1", group: "content" },
      { type: "text", key: "f2Title", label: "Заголовок 2", group: "content" },
      { type: "textarea", key: "f2Text", label: "Текст 2", group: "content" },
      { type: "text", key: "f3Title", label: "Заголовок 3", group: "content" },
      { type: "textarea", key: "f3Text", label: "Текст 3", group: "content" },
      { type: "color", key: "bg", label: "Фон", group: "style" },
      { type: "color", key: "textColor", label: "Цвет текста", group: "style" },
      { type: "color", key: "accent", label: "Акцентный цвет", group: "style" },
    ],
  },
  {
    type: "text-image",
    name: "Текст + картинка",
    category: "Контент",
    defaultProps: {
      title: "О нас",
      text: "Расскажите о своей команде, миссии или продукте. Этот блок отлично подходит для подробностей.",
      image: "",
      reverse: false,
      bg: "#ffffff",
      textColor: "#111827",
      accent: "#2563eb",
    },
    fields: [
      { type: "text", key: "title", label: "Заголовок", group: "content" },
      { type: "textarea", key: "text", label: "Текст", group: "content" },
      { type: "image", key: "image", label: "Картинка", aspect: "square", group: "content" },
      { type: "toggle", key: "reverse", label: "Картинка справа", group: "style" },
      { type: "color", key: "bg", label: "Фон", group: "style" },
      { type: "color", key: "textColor", label: "Цвет текста", group: "style" },
      { type: "color", key: "accent", label: "Акцентный цвет", group: "style" },
    ],
  },
  {
    type: "text",
    name: "Текст",
    category: "Контент",
    defaultProps: {
      title: "Заголовок раздела",
      text: "Текст абзаца. Здесь можно разместить основное содержимое раздела.",
      bg: "#ffffff",
      textColor: "#111827",
      align: "left",
      paddingY: 64,
    },
    fields: [
      { type: "text", key: "title", label: "Заголовок", group: "content" },
      { type: "textarea", key: "text", label: "Текст", group: "content" },
      { type: "align", key: "align", label: "Выравнивание", group: "style" },
      { type: "color", key: "bg", label: "Фон", group: "style" },
      { type: "color", key: "textColor", label: "Цвет текста", group: "style" },
      { type: "number", key: "paddingY", label: "Вертикальный отступ", unit: "px", min: 0, max: 240, step: 8, group: "style" },
    ],
  },
  {
    type: "gallery",
    name: "Галерея",
    category: "Медиа",
    defaultProps: {
      title: "Галерея",
      columns: "3",
      gap: 16,
      bg: "#ffffff",
      textColor: "#111827",
      img1: "", img2: "", img3: "",
      img4: "", img5: "", img6: "",
    },
    fields: [
      { type: "text", key: "title", label: "Заголовок", group: "content" },
      { type: "select", key: "columns", label: "Колонок", group: "style", options: [
        { label: "2 колонки", value: "2" },
        { label: "3 колонки", value: "3" },
        { label: "4 колонки", value: "4" },
      ]},
      { type: "image", key: "img1", label: "Картинка 1", aspect: "square", group: "content" },
      { type: "image", key: "img2", label: "Картинка 2", aspect: "square", group: "content" },
      { type: "image", key: "img3", label: "Картинка 3", aspect: "square", group: "content" },
      { type: "image", key: "img4", label: "Картинка 4", aspect: "square", group: "content" },
      { type: "image", key: "img5", label: "Картинка 5", aspect: "square", group: "content" },
      { type: "image", key: "img6", label: "Картинка 6", aspect: "square", group: "content" },
      { type: "color", key: "bg", label: "Фон", group: "style" },
      { type: "color", key: "textColor", label: "Цвет текста", group: "style" },
    ],
  },
  {
    type: "pricing",
    name: "Тарифы",
    category: "Контент",
    defaultProps: {
      title: "Тарифы",
      subtitle: "Выберите подходящий план",
      p1Name: "Базовый", p1Price: "490 ₽", p1Features: "1 сайт\nБазовая поддержка",
      p2Name: "Про", p2Price: "990 ₽", p2Features: "5 сайтов\nВсе блоки\nПриоритетная поддержка",
      p3Name: "Бизнес", p3Price: "1990 ₽", p3Features: "Без ограничений\nКомандная работа\nAPI",
      buttonText: "Выбрать",
      bg: "#ffffff",
      textColor: "#111827",
      accent: "#2563eb",
    },
    fields: [
      { type: "text", key: "title", label: "Заголовок", group: "content" },
      { type: "text", key: "subtitle", label: "Подзаголовок", group: "content" },
      { type: "text", key: "p1Name", label: "Тариф 1: название", group: "content" },
      { type: "text", key: "p1Price", label: "Тариф 1: цена", group: "content" },
      { type: "textarea", key: "p1Features", label: "Тариф 1: пункты (по строке)", group: "content" },
      { type: "text", key: "p2Name", label: "Тариф 2: название", group: "content" },
      { type: "text", key: "p2Price", label: "Тариф 2: цена", group: "content" },
      { type: "textarea", key: "p2Features", label: "Тариф 2: пункты (по строке)", group: "content" },
      { type: "text", key: "p3Name", label: "Тариф 3: название", group: "content" },
      { type: "text", key: "p3Price", label: "Тариф 3: цена", group: "content" },
      { type: "textarea", key: "p3Features", label: "Тариф 3: пункты (по строке)", group: "content" },
      { type: "text", key: "buttonText", label: "Текст кнопки", group: "content" },
      { type: "color", key: "bg", label: "Фон", group: "style" },
      { type: "color", key: "textColor", label: "Цвет текста", group: "style" },
      { type: "color", key: "accent", label: "Акцентный цвет", group: "style" },
    ],
  },
  {
    type: "faq",
    name: "Вопрос-ответ",
    category: "Контент",
    defaultProps: {
      title: "Частые вопросы",
      q1: "Как это работает?", a1: "Ответ на первый вопрос.",
      q2: "Сколько это стоит?", a2: "Ответ на второй вопрос.",
      q3: "Есть ли поддержка?", a3: "Ответ на третий вопрос.",
      bg: "#ffffff",
      textColor: "#111827",
      accent: "#2563eb",
    },
    fields: [
      { type: "text", key: "title", label: "Заголовок", group: "content" },
      { type: "text", key: "q1", label: "Вопрос 1", group: "content" },
      { type: "textarea", key: "a1", label: "Ответ 1", group: "content" },
      { type: "text", key: "q2", label: "Вопрос 2", group: "content" },
      { type: "textarea", key: "a2", label: "Ответ 2", group: "content" },
      { type: "text", key: "q3", label: "Вопрос 3", group: "content" },
      { type: "textarea", key: "a3", label: "Ответ 3", group: "content" },
      { type: "color", key: "bg", label: "Фон", group: "style" },
      { type: "color", key: "textColor", label: "Цвет текста", group: "style" },
      { type: "color", key: "accent", label: "Акцентный цвет", group: "style" },
    ],
  },
  {
    type: "cta",
    name: "Призыв к действию",
    category: "Контент",
    defaultProps: {
      title: "Готовы начать?",
      subtitle: "Создайте свой сайт уже сегодня.",
      buttonText: "Связаться",
      bg: "#2563eb",
      textColor: "#ffffff",
      buttonColor: "#ffffff",
      buttonTextColor: "#2563eb",
    },
    fields: [
      { type: "text", key: "title", label: "Заголовок", group: "content" },
      { type: "text", key: "subtitle", label: "Подзаголовок", group: "content" },
      { type: "text", key: "buttonText", label: "Текст кнопки", group: "content" },
      { type: "color", key: "bg", label: "Фон", group: "style" },
      { type: "color", key: "textColor", label: "Цвет текста", group: "style" },
      { type: "color", key: "buttonColor", label: "Цвет кнопки", group: "style" },
      { type: "color", key: "buttonTextColor", label: "Цвет текста кнопки", group: "style" },
    ],
  },
  {
    type: "footer",
    name: "Подвал",
    category: "Структура",
    defaultProps: {
      brand: "Логотип",
      text: "Краткое описание компании или проекта.",
      copyright: "© 2026. Все права защищены.",
      bg: "#111827",
      textColor: "#9ca3af",
    },
    fields: [
      { type: "text", key: "brand", label: "Название", group: "content" },
      { type: "textarea", key: "text", label: "Описание", group: "content" },
      { type: "text", key: "copyright", label: "Копирайт", group: "content" },
      { type: "color", key: "bg", label: "Фон", group: "style" },
      { type: "color", key: "textColor", label: "Цвет текста", group: "style" },
    ],
  },
];
